a = input('digite algo: ')
print('O tipo primitivo desse vaçor é', type(a))
print('Só tem espaços?', a.isspace())
print('é um número? ', a.isnumeric())
print('é alfabético? ', a.isalpha())
print('é Alfanumérico?', a.isalnum())
print('está em maiúsculas?', a.isupper())
print('está em minúsculas?', a.islower())
print('Está Capitalizada?', a.istitle())